# Generated by Django 4.1.2 on 2022-10-19 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teg',
            options={'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
        migrations.RenameField(
            model_name='teg',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='teg',
            name='article',
            field=models.ManyToManyField(related_name='tegs', through='articles.Scope', to='articles.article'),
        ),
    ]
