# Generated by Django 4.1.2 on 2022-10-17 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_alter_student_teachers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='teachers',
            new_name='teacher',
        ),
    ]
