# Generated by Django 4.1.2 on 2022-10-17 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_rename_teachers_student_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='teacher',
            new_name='teachers',
        ),
    ]
